from __future__ import annotations

import os
import warnings
from pathlib import Path
import shutil
from typing import Optional
from dataclasses import dataclass, field

import pandas as pd

from pymatgen.core import Structure
from pymatgen.io.vasp.inputs import Incar, Kpoints
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.io.ase import AseAtomsAdaptor

from ase import Atoms

import flowrep as fr

from pyiron_workflow_vasp.generic import (
    compress_directory,
    delete_files_recursively,
    remove_directory,
    run_shell,
)

from pyiron_snippets.logger import logger

def read_potcar_config(config_file: Path) -> dict:
    """
    Reads the POTCAR configuration from a file and resolves the paths dynamically based on config content.

    Args:
        config_file (Path): Path to the configuration file.

    Returns:
        dict: A dictionary containing the resolved paths and the default POTCAR path.

    Raises:
        ValueError:
            - If no valid `default_POTCAR_set` is found in the config file.
            - If no valid `default_functional` (e.g., GGA or LDA) is found in the config.
        FileNotFoundError: If the configuration file does not exist.
        Exception: For any other unexpected issues encountered while reading the file.
    """

    config_data = {}

    # Read the configuration file
    try:
        with open(config_file, "r") as f:
            for line in f:
                # Skip comments and empty lines
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                # Split the line into key and value
                if "=" in line:
                    key, value = line.split("=", 1)
                    key = key.strip()
                    value = value.strip()

                    # Store the configuration
                    config_data[key] = value

        # Resolve the pyiron_vasp_resources path
        pyiron_vasp_resources = config_data.get("pyiron_vasp_resources", "")
        default_POTCAR_set = config_data.get("default_POTCAR_set")
        default_functional = config_data.get("default_functional")

        # Dynamically identify all POTCAR sets based on keys in the config file
        potcar_sets = []
        for key in config_data:
            if key.startswith("vasp_POTCAR_path_"):
                potcar_sets.append(key.split("vasp_POTCAR_path_")[1])

        # Check if a valid default_POTCAR_set is provided
        if not default_POTCAR_set or default_POTCAR_set not in potcar_sets:
            raise ValueError(
                f"Unknown or missing default_POTCAR_set: {default_POTCAR_set}. Valid options: {potcar_sets}"
            )

        # Check if a valid default_functional is provided
        if not default_functional or default_functional not in ["GGA", "LDA"]:
            raise ValueError(
                f"Unknown or missing default_functional: {default_functional}. Valid options: GGA, LDA"
            )

        # Dynamically generate the paths for all potpaw sets based on the config content
        for potcar_set in potcar_sets:
            key = f"vasp_POTCAR_path_{potcar_set}"
            # Preserve the underscores in the path
            config_data[key] = os.path.join(
                pyiron_vasp_resources, potcar_set.replace("potpaw", "potpaw_")
            )

        # Set the default POTCAR path
        config_data["default_POTCAR_path"] = config_data[
            f"vasp_POTCAR_path_{default_POTCAR_set}"
        ]

        return config_data

    except FileNotFoundError as e:
        raise FileNotFoundError(f"Configuration file not found: {config_file}") from e
    except ValueError as e:
        raise e  # Let specific ValueErrors propagate
    except Exception as e:
        raise Exception(f"Error reading configuration file: {e}") from e


# Look in user's home dir
config_file = os.path.join(Path.home(), ".pyiron_vasp_config")
potcar_config = read_potcar_config(config_file)
default_POTCAR_library_path = potcar_config["default_POTCAR_path"]
default_POTCAR_generation_path = os.path.join(
    potcar_config["default_POTCAR_path"], potcar_config["default_functional"]
)
default_functional = potcar_config["default_functional"]
POTCAR_default_specification_data = str(
    Path(__file__).parent.joinpath(
        "vasp_resources", f"vasp_pseudopotential_{default_functional}_data.csv"
    )
)


@dataclass
class VaspInput:
    """
    Class to represent the input settings for a VASP calculation, including structure, INCAR parameters, and pseudopotential paths.

    Attributes:
        structure (ase Atoms): The atomic structure of the system to be used in the VASP calculation.
        incar (pymatgen Incar): The INCAR object containing the VASP input parameters.
        pseudopot_lib_path (str): The path to the library of VASP pseudopotentials (POTCAR files).
        Defaults to `default_POTCAR_generation_path` generated by the .pyiron_vasp_config.
        potcar_paths (Optional[list[str]]): A list of paths to user-specified POTCAR files associated with the calculation.
            When specified, this _OVERRIDES_ default POTCAR generation.
            This list must contain all the necessary POTCAR files for the elements in the structure.
            For example, if the structure contains H O H atoms, the list should contain paths like:
            - ".../vasp/potpaw_64/H/POTCAR"
            - ".../vasp/custom_charged_potential/O/POTCAR"
            - ".../vasp/potpaw_64/H/POTCAR"
            No checks are performed to ensure the POTCAR files match the species in the structure, so it is the user's responsibility
            to ensure consistency between the elements in the structure and the provided POTCAR files when using this functionality.

        kpoints (Optional[Kpoints]): The KPOINTS object defining the k-point mesh for the calculation. If not provided, default settings will be used.

    Notes:
        - The `potcar_paths` attribute is exposed to allow users to make one-off changes to the pseudopotentials. This is
          useful when custom/non-default potentials are required for specific elements.
        - When potcar_paths is used, the class does not validate that the provided POTCAR files match the elements in the structure,
          so incorrect configurations may lead to invalid calculations.
        - ``structure`` may be given as either an ``ase.Atoms`` or a ``pymatgen.core.Structure``; ``__post_init__``
          normalizes a pymatgen ``Structure`` to ``ase.Atoms`` once, at construction, since the file-writing helpers
          (``write_POSCAR``, ``get_default_POTCAR_paths``) only understand ``ase.Atoms``. The normalization never
          mutates the object the caller passed in.
        - **Per-site magnetic moments are NOT propagated to the INCAR.** If ``structure`` carries
          ``site_properties={"magmom": ...}`` (pymatgen) or per-atom initial magnetic moments (ase), those are
          silently dropped -- neither the ase nor the pymatgen write path ever wrote a MAGMOM tag from the
          structure. Set MAGMOM explicitly as an INCAR string (e.g. ``"3*2.5 1*-2.5"``) if the calculation needs it;
          this is the contract downstream ASSYST campaigns already rely on.
    """

    structure: Atoms
    incar: Incar
    pseudopot_lib_path: str = field(default=default_POTCAR_library_path)
    pseudopot_functional: str = "GGA"
    potcar_paths: Optional[list[str]] = None
    kpoints: Optional[Kpoints] = None
    # generic_input: GenericDFTInput
#    spin_constraints: []

    def __post_init__(self):
        # Normalize once, at construction, so every producer of a VaspInput
        # (generate_vasp_input, construct_sequential_vasp_input, or direct
        # construction by a caller/test) ends up with an ase.Atoms structure
        # regardless of what representation it was handed. This never
        # mutates the caller's original object -- AseAtomsAdaptor.get_atoms
        # returns a new object; self.structure is simply rebound.
        if isinstance(self.structure, Structure):
            self.structure = AseAtomsAdaptor.get_atoms(self.structure)

# def GenericDFTInput:
#     spin_constraints=[]
#     kpoints=[]
#     plane_wave_cutoff=[]

def write_POSCAR(workdir: str, structure: Atoms, filename: str = "POSCAR") -> str:
    poscar_path = os.path.join(workdir, filename)
    # structure.to(fmt="poscar", filename=poscar_path)
    structure.write(poscar_path, format="vasp")
    return poscar_path


def write_INCAR(workdir: str, incar: Incar, filename: str = "INCAR") -> str:
    incar_path = os.path.join(workdir, filename)
    incar.write_file(incar_path)
    return incar_path


def write_POTCAR(workdir: str, vasp_input: VaspInput, filename: str = "POTCAR") -> str:
    class PotcarNotGeneratedError(Exception):
        pass

    if vasp_input.potcar_paths is None:
        potcar_paths = get_default_POTCAR_paths(
            vasp_input.structure, pseudopot_lib_path=vasp_input.pseudopot_lib_path, pseudopot_functional=vasp_input.pseudopot_functional
        )
    else:
        potcar_paths = vasp_input.potcar_paths

    potcar_path = os.path.join(workdir, filename)

    with open(potcar_path, "wb") as wfd:
        for f in potcar_paths:
            with open(f, "rb") as fd:
                shutil.copyfileobj(fd, wfd)

    return potcar_path


def write_KPOINTS(
    workdir: str, kpoints: Optional[Kpoints] = None, filename: str = "KPOINTS"
) -> str:
    kpoint_path = os.path.join(workdir, filename)
    if kpoints is not None:
        kpoints.write_file(kpoint_path)
    else:
        with open(kpoint_path, "w") as f:
            f.write(
                "Automatic mesh\n0\nGamma\n1 1 1\n0 0 0\n"
            )  # Example KPOINTS content
    return kpoint_path


@fr.atomic("workdir")
def create_working_directory(workdir: str, quiet: bool = False) -> str:
    """Create ``workdir`` if absent. Must be given an absolute path."""
    if not os.path.exists(workdir):
        os.makedirs(workdir)
        logger.info(f"made directory '{workdir}'")
    elif not quiet:
        warnings.warn(
            f"Directory '{workdir}' already exists. Existing files may be overwritten."
        )
    return workdir


@fr.atomic("workdir")
def write_vasp_input_set(workdir: str, vasp_input: VaspInput) -> str:
    # vasp_input.structure is already an ase.Atoms here: VaspInput.__post_init__
    # normalizes a pymatgen Structure once, at construction, for every producer.
    write_POSCAR(workdir=workdir, structure=vasp_input.structure)
    write_INCAR(workdir=workdir, incar=vasp_input.incar)
    write_POTCAR(workdir=workdir, vasp_input=vasp_input)
    if vasp_input.kpoints is not None:
        write_KPOINTS(workdir=workdir, kpoints=vasp_input.kpoints)
    return workdir


@fr.atomic("output_dict")
def parse_vasp_output(
    workdir: str,
    function=None,
    parser_args: dict | None = None,
    after: object = None,
) -> dict | pd.DataFrame:
    """Parse VASP output. ``after`` is an ordering token; see generic.py.

    Returns whatever ``function`` returns when supplied. The default parser
    (``vasp_parser.output.parse_vasp_directory``) returns a ``pandas.DataFrame``,
    not a ``dict`` -- despite the ``"output_dict"`` port name, which predates
    this port and is kept for compatibility with existing callers/tests.
    """
    if function is None:
        from pyiron_workflow_vasp.vasp_parser.output import parse_vasp_directory

        return parse_vasp_directory(workdir)
    return function(**(parser_args or {}))


@fr.atomic("convergence")
def check_convergence(
    workdir: str,
    filename_vasprun: str = "vasprun.xml",
    filename_vasplog: str = "vasp.log",
    backup_vasplog: str = "error.out",
    after: object = None,
) -> bool:
    """Report whether the calculation reached ionic convergence."""
    line_converged = "reached required accuracy - stopping structural energy minimisation"
    try:
        return bool(Vasprun(filename=os.path.join(workdir, filename_vasprun)).converged)
    except Exception:
        pass
    for candidate in (filename_vasplog, backup_vasplog):
        path = os.path.join(workdir, candidate)
        if os.path.isfile(path):
            with open(path) as handle:
                if any(line_converged in line for line in handle):
                    return True
    return False


@fr.workflow("vasp_output", "convergence_status")
def vasp_job(
    workdir: str,
    vasp_input: VaspInput,
    command: str = "mpiexec -n 1 vasp_std",
    files_to_be_deleted: list[str] | None = None,
    compress: bool = False,
    compressed_file_in_dir: bool = False,
    remove_calc_dir: bool = False,
    vasp_parser_function=None,
    vasp_parser_args: dict | None = None,
):
    """Run one VASP calculation and return its parsed output and convergence.

    pyiron_workflow 0.19 removed execution signals, so the ordering that the
    0.11 macro expressed with ``>>`` is rebuilt here as data dependencies. The
    ``after=`` arguments are ordering tokens that are never read by the
    receiving node; they exist only to create the edge.
    """
    wd_created = create_working_directory(workdir)
    wd_written = write_vasp_input_set(wd_created, vasp_input)
    shell_result = run_shell(command, wd_written)
    raw_output = parse_vasp_output(
        wd_written, vasp_parser_function, vasp_parser_args, after=shell_result
    )
    convergence = check_convergence(wd_written, after=shell_result)
    # NOTE: there is no explicit data edge from `convergence` into
    # delete_files_recursively below (it is ordered after `raw_output` /
    # parse_vasp_output instead, not after check_convergence). That is safe
    # ONLY because 0.19's DAG-layer barrier places delete_files_recursively
    # in a layer after check_convergence has already run, so convergence is
    # always read before any deletion happens -- this is a dependency on
    # executor/layering semantics, not on a data edge. If a future edit
    # changes the execution model (e.g. separate executors without a shared
    # layer barrier) this ordering guarantee disappears silently; add an
    # explicit `after=convergence` edge if that assumption is ever relaxed.
    wd_cleaned = delete_files_recursively(
        wd_written, files_to_be_deleted, after=raw_output
    )
    wd_archived = compress_directory(
        wd_cleaned, compress, compressed_file_in_dir, after=convergence
    )
    vasp_output = remove_directory(wd_archived, remove_calc_dir, raw_output)
    return vasp_output, convergence


def stack_element_string(structure) -> tuple[list[str], list[int]]:
    #site_element_list = [site.species_string for site in structure]
    site_element_list = [atom.symbol for atom in structure]
    past_element = site_element_list[0]
    element_list = [past_element]
    element_count = []
    count = 0

    for element in site_element_list:
        if element == past_element:
            count += 1
        else:
            element_count.append(count)
            element_list.append(element)
            count = 1
            past_element = element

    element_count.append(count)
    return element_list, element_count


def get_default_POTCAR_paths(
    structure: Atoms,
    pseudopot_lib_path: str,
    pseudopot_functional: str = "GGA",
    potcar_df: pd.DataFrame = pd.read_csv(POTCAR_default_specification_data),
) -> list[str]:
    ele_list, _ = stack_element_string(structure)
    potcar_paths = []
    for element in ele_list:
        ele_default_potcar_path = potcar_df[
            (potcar_df["symbol"] == element) & (potcar_df["default"] == True)
        ].potential_name.values[0]
        potcar_paths.append(
            os.path.join(pseudopot_lib_path, pseudopot_functional, ele_default_potcar_path, "POTCAR")
        )

    return potcar_paths


#%% These are utilities
@fr.atomic("incar")
def generate_modified_incar(incar: Incar, modifications: dict) -> Incar:
    """Return a copy of ``incar`` with ``modifications`` applied.

    Copies rather than mutating: the same INCAR object is fanned out to many
    nodes, and 0.19 evaluates sibling nodes concurrently.
    """
    modified = Incar.from_dict(dict(incar))
    for key, value in modifications.items():
        modified[key] = value
    return modified


@fr.atomic("vasp_input")
def generate_vasp_input(structure, incar: Incar, potcar_paths=None) -> VaspInput:
    return VaspInput(structure=structure, incar=incar, potcar_paths=potcar_paths)


@fr.atomic("vasp_input")
def construct_sequential_vasp_input(
    vasp_output: pd.DataFrame, incar: Incar, potcar_paths=None
) -> VaspInput:
    """Takes the most recent calculation in the directory and its final
    ionic step, and builds the next VaspInput from it.

    ``vasp_output`` is the DataFrame produced by ``parse_vasp_output`` (see
    ``vasp_parser/output.py``, ``parse_vasp_directory``): one row per
    OUTCAR* found plus one row per error archive, sorted ASCENDING by
    ``calc_start_time``. Its ``structures`` column holds, per row, an array
    of ``Structure.to_json()`` strings, one per ionic step -- NOT structure
    objects.

    ``.iloc[-1]`` selects the LAST row, i.e. the most recent calculation,
    not ``.iloc[0]`` (the oldest/earliest). This matters whenever a
    directory holds more than one row -- e.g. a custodian restart or an
    error archive -- such as ASSYST's ISIF7 -> ISIF5 -> ISIF2 chains run
    with max_errors>0: picking the oldest row would feed the
    crashed/earliest attempt's structure into the next stage instead of
    continuing from where the calculation actually left off.
    ``vasp_output.structures.iloc[-1][-1]`` is therefore the JSON string for
    the last ionic step of the most recent row, and must be round-tripped
    back through ``Structure.from_str(..., fmt="json")`` before it is
    usable. ``VaspInput.__post_init__`` then normalizes that pymatgen
    Structure to ase.Atoms, same as every other VaspInput producer.
    """
    # str(...): parse_vasp_directory stores the per-step JSON strings in a
    # numpy array, so indexing it back out yields numpy.str_ rather than a
    # plain str. pymatgen's JSON reader (orjson) rejects numpy.str_ even
    # though it is a str subclass, so it must be coerced explicitly.
    structure = Structure.from_str(
        str(vasp_output.structures.iloc[-1][-1]), fmt="json"
    )
    return VaspInput(structure=structure, incar=incar, potcar_paths=potcar_paths)
